#!/bin/bash

set -u

function ioloop() {
    FIFO=$(mktemp -u /tmp/ioloop_$$_XXXXXX ) &&
    trap "rm -f ${FIFO}" EXIT &&
    mkfifo ${FIFO} &&
    ( : <${FIFO} & ) &&    # avoid deadlock on opening pipe
    exec >${FIFO} <${FIFO}
}

function test() {
    NAME=$1
    RUN_PROGRAM="$2"
    (
        cd `dirname $0`
    
        echo -n "Test ${NAME}: "
        for ANS in '9 8 7 6' '7 6 5 9' '8 0 3 7' '0 1 2 3' '6 5 2 1' '8 4 0 9'; do
            ( ioloop && ./judge ${ANS} | ${RUN_PROGRAM} )
            STATUS=$?
            if [ 0 -ne ${STATUS} ]; then
                echo "Test failed: ${ANS} (status ${STATUS})"
            else
                echo -n "."
            fi
        done
        echo ""
    )
}

test 'Ruby' 'ruby 0355.rb'
#test 'D   ' './d0355'
