#!/usr/bin/env ruby

require 'nokogiri'
require 'open-uri'
require 'fileutils'

def main
  if 1 != ARGV.size
    warn "usage: #{__FILE__} PROBLEM_ID"
    exit 1
  end
  problem_id = ARGV.shift.to_i

  dir = "#{File.dirname(__FILE__)}/#{sprintf("%04d", problem_id)}"
  FileUtils.mkdir(dir) unless File.exist?(dir)

  download_create_sample_data_files(dir, problem_id)
end

def download_create_sample_data_files(dir, problem_id)
  url = "http://yukicoder.me/problems/no/#{problem_id}"
  html = open(url).read
  doc = Nokogiri::HTML(html, url)
  doc.css('.sample').enum_for(:each).with_index do |sample, i|
    input, output = sample.css('.paragraph pre').map{|node| node.inner_html.strip.gsub('<br>', "\n") }
    basename = "#{dir}/0_sample#{i+1}"
    open("#{basename}.in", 'w') do |f|
      f.puts input
    end
    open("#{basename}.out", 'w') do |f|
      f.puts output
    end
  end
end

main
