#!/bin/bash

set -u

if [ $# -lt 1 ]; then
    echo "usage: $0 0001 0002 ..." >&2
    exit 1
fi

function main () {
    for PROBLEM_ID in $*; do
        if [ ! -e ${PROBLEM_ID}/ ]; then
            echo "${PROBLEM_ID} NO TestCase" 1>&2
            continue
        fi

        generate_testcases_for ${PROBLEM_ID}
        run_test_for ${PROBLEM_ID}
    done
}

function generate_testcases_for () {
    PROBLEM_ID=$1

    (
        cd ${PROBLEM_ID}

        ls gen_*.rb >/dev/null 2>&1
        if [ 0 -eq $? ]; then
            for SCRIPT in gen_*.rb; do
                ruby ${SCRIPT}
            done
        fi

        ls *.erb >/dev/null 2>&1
        if [ 0 -eq $? ]; then
            for ERB in *.erb; do
                ERB_OUTPUT_FILE=_`echo ${ERB} | sed "s/\.erb$//"`
                erb ${ERB} > ${ERB_OUTPUT_FILE}
            done
        fi
    )
}

function run_test_for () {
    PROBLEM_ID=$1

    BIN=./${PROBLEM_ID}.exe
    if [ ! -e ${BIN} ]; then
        BIN="ruby ${PROBLEM_ID}.rb"
    fi

    echo -n "${PROBLEM_ID} "
    for TEST_INPUT in ${PROBLEM_ID}/*.input; do
        run_testcase ${PROBLEM_ID} "${BIN}" ${TEST_INPUT}
    done
    echo ""
}

function run_testcase () {
    PROBLEM_ID=$1
    BIN="$2"
    TEST_INPUT=$3

    TEST_NAME=`echo ${TEST_INPUT} | sed "s/^${PROBLEM_ID}\///" | sed "s/\.input$//"`
    TEST_OUTPUT=${PROBLEM_ID}/${TEST_NAME}.output

    if [ -e ${TEST_OUTPUT} ]; then
        ${BIN} < ${TEST_INPUT} | diff -u ${TEST_OUTPUT} -
    else
        ${BIN} < ${TEST_INPUT} >/dev/null
    fi
    STATUS=$?
    if [ 0 -ne ${STATUS} ]; then
        echo "Test failed: ${TEST_NAME} (status ${STATUS})"
    else
        echo -n "."
    fi
}

main $*
