#!/bin/bash

set -u

function ioloop() {
    FIFO=$(mktemp -u /tmp/ioloop_$$_XXXXXX ) &&
    trap "rm -f ${FIFO}" EXIT &&
    mkfifo ${FIFO} &&
    ( : <${FIFO} & ) &&    # avoid deadlock on opening pipe
    exec >${FIFO} <${FIFO}
}

function test() {
    NAME=$1
    RUN_PROGRAM="$2"
    (
        cd `dirname $0`
    
        echo -n "Test ${NAME}: "
        for ANS in 1 2 3 9 10 50 99 100 1000 10000 100000 1000000 10000000 100000000 500000000 999999999 1000000000; do
            ( ioloop && ./judge ${ANS} | ${RUN_PROGRAM} )
            STATUS=$?
            if [ 0 -ne ${STATUS} ]; then
                echo "Test failed: ${ANS} (status ${STATUS})"
            else
                echo -n "."
            fi
        done
        echo ""
    )
}

test 'Ruby' 'ruby 0246.rb'
test 'D   ' './d0246'
